name: PR Conventional Commit Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  connected-tests:
    runs-on: macos-latest

    steps:
      - name: Ensure tests checkbox is checked
        run: |
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q ".body")
          echo "$PR_BODY" | grep -q '\[x\] Run tests' || {
            echo 'Tests disabled. Please check the "Run tests" checkbox in the PR description.'
            exit 1
          }
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
