name: Check code

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure tests checkbox is checked
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            if (!body.includes('- [x] Run tests')) {
              core.setFailed('The "Run PR name check" box must be checked in the PR description.');
            }

      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          script: ./gradlew connectedCheck

